"""Legacy-compatible import path for the Plyctl public SDK."""

from .buffers import BufferPool
from .cv_types import ManagedBuffer, MemoryType, register_message_type
from .device import DmaBufHandle, DmaBufPlane
from .memory import (
    CudaIpcHandle,
    ExternalMemoryHandle,
    MemoryAccess,
    MemoryPlan,
    MemoryRequirement,
    memory_summary,
    plan_memory,
)
from .messages import Message
from .errors import (
    ManifestError,
    NodrixError,
    PlyctlError,
    PluginError,
    ProviderError,
    RuntimeGraphError,
)
from .manifest import (
    EdgeConfig,
    ExternalLinkConfig,
    ApplicationConfig,
    NodeConfig,
    PipelineManifest,
    QueueConfig,
    SessionConfig,
    ProviderResourceConfig,
    TransportConfig,
    load_manifest,
    load_manifest_details,
    load_fragment,
)
from .shared_memory import SharedBufferDescriptor, SharedBufferPool
from .node import Node, NodeContext, SinkNode, SourceNode
from .session import Session, SessionContext
from .integration import (
    ApplicationContext,
    ManagedApplication,
    ManagedResource,
    ResourceContext,
)
from .lifecycle import HealthStatus, LifecycleState
from .wire import register_wire_codec
from .provider_api import (
    PROVIDER_API_VERSION,
    PROVIDER_ENTRY_POINT_GROUP,
    PROVIDER_SCHEMA,
    PROVIDER_API_VERSION_V2,
    PROVIDER_SCHEMA_V2,
    PLYCTL_PROVIDER_ENTRY_POINT_GROUP,
    PLYCTL_PROVIDER_SCHEMA,
    PLYCTL_PROVIDER_SCHEMA_V2,
    SUPPORTED_PROVIDER_ENTRY_POINT_GROUPS,
    FeatureNegotiation,
    NodeDescriptor,
    ProbeDescriptor,
    SessionDescriptor,
    ResourceDescriptor,
    ApplicationDescriptor,
    LinkDescriptor,
    TransportDescriptor,
    ProviderManifest,
    ProviderMetadata,
    ProviderRuntime,
    TemplateDescriptor,
    negotiate_features,
)
from .branding import MANIFEST_API_V1, MANIFEST_API_V2

__all__ = [
    "Message",
    "Node",
    "NodeContext",
    "SourceNode",
    "SinkNode",
    "Session",
    "SessionContext",
    "ApplicationContext",
    "ManagedApplication",
    "ManagedResource",
    "ResourceContext",
    "BufferPool",
    "SharedBufferPool",
    "SharedBufferDescriptor",
    "ManagedBuffer",
    "MemoryType",
    "MemoryAccess",
    "MemoryRequirement",
    "MemoryPlan",
    "DmaBufPlane",
    "DmaBufHandle",
    "CudaIpcHandle",
    "ExternalMemoryHandle",
    "plan_memory",
    "memory_summary",
    "register_message_type",
    "register_wire_codec",
    "LifecycleState",
    "HealthStatus",
    "PipelineManifest",
    "NodeConfig",
    "EdgeConfig",
    "ExternalLinkConfig",
    "ApplicationConfig",
    "QueueConfig",
    "SessionConfig",
    "ProviderResourceConfig",
    "TransportConfig",
    "load_manifest",
    "load_manifest_details",
    "load_fragment",
    "NodrixError",
    "PlyctlError",
    "ManifestError",
    "PluginError",
    "ProviderError",
    "RuntimeGraphError",
    "PROVIDER_API_VERSION",
    "PROVIDER_ENTRY_POINT_GROUP",
    "PROVIDER_SCHEMA",
    "PROVIDER_API_VERSION_V2",
    "PROVIDER_SCHEMA_V2",
    "PLYCTL_PROVIDER_ENTRY_POINT_GROUP",
    "PLYCTL_PROVIDER_SCHEMA",
    "PLYCTL_PROVIDER_SCHEMA_V2",
    "SUPPORTED_PROVIDER_ENTRY_POINT_GROUPS",
    "MANIFEST_API_V1",
    "MANIFEST_API_V2",
    "ProviderMetadata",
    "NodeDescriptor",
    "ProbeDescriptor",
    "SessionDescriptor",
    "ResourceDescriptor",
    "ApplicationDescriptor",
    "LinkDescriptor",
    "TransportDescriptor",
    "TemplateDescriptor",
    "ProviderManifest",
    "ProviderRuntime",
    "FeatureNegotiation",
    "negotiate_features",
]

__version__ = "2.3.0b1"
