"""Stable Plyctl 2.x manifest facade.

Implementation is split between immutable/validated models and parsing,
normalization, diagnostics, and serialization services. Existing imports from
``nodrix.manifest`` remain supported throughout Plyctl 2.x.
"""

from .manifest_io import (
    ManifestDiagnostic,
    ManifestLoadResult,
    _redact,
    dump_manifest,
    dump_manifest_redacted,
    dump_source_manifest_redacted,
    load_manifest,
    load_manifest_details,
)
from .manifest_model import (
    ApplicationConfig,
    EdgeConfig,
    EdgeMemoryConfig,
    ExecutionConfig,
    ExternalLinkConfig,
    FailureConfig,
    FragmentConfig,
    HealthConfig,
    LoggingConfig,
    MemoryDomain,
    MetadataConfig,
    MetricsConfig,
    NodeConfig,
    NodeMemoryConfig,
    PipelineManifest,
    PlacementConfig,
    ProviderResourceConfig,
    QueueConfig,
    RecordingConfig,
    ResourceConfig,
    RuntimeConfig,
    RuntimeMemoryConfig,
    SecurityConfig,
    SessionConfig,
    SharedPoolConfig,
    ShutdownConfig,
    StreamAccessConfig,
    StreamExportConfig,
    StreamsConfig,
    StreamTlsConfig,
    StrictModel,
    SynchronizationConfig,
    TracingConfig,
    TransportConfig,
    UsesConfig,
    _ENV_RE,
    _expand_env,
)
from .manifest_parser import (
    canonical_config_path,
    external_transport_bindings,
    load_block,
    load_fragment,
)


__all__ = [
    "ApplicationConfig",
    "EdgeConfig",
    "EdgeMemoryConfig",
    "ExecutionConfig",
    "ExternalLinkConfig",
    "FailureConfig",
    "FragmentConfig",
    "HealthConfig",
    "LoggingConfig",
    "ManifestDiagnostic",
    "ManifestLoadResult",
    "MemoryDomain",
    "MetadataConfig",
    "MetricsConfig",
    "NodeConfig",
    "NodeMemoryConfig",
    "PipelineManifest",
    "PlacementConfig",
    "ProviderResourceConfig",
    "QueueConfig",
    "RecordingConfig",
    "ResourceConfig",
    "RuntimeConfig",
    "RuntimeMemoryConfig",
    "SecurityConfig",
    "SessionConfig",
    "SharedPoolConfig",
    "ShutdownConfig",
    "StreamAccessConfig",
    "StreamExportConfig",
    "StreamsConfig",
    "StreamTlsConfig",
    "StrictModel",
    "SynchronizationConfig",
    "TracingConfig",
    "TransportConfig",
    "UsesConfig",
    "canonical_config_path",
    "dump_manifest",
    "dump_manifest_redacted",
    "dump_source_manifest_redacted",
    "external_transport_bindings",
    "load_block",
    "load_fragment",
    "load_manifest",
    "load_manifest_details",
    "_ENV_RE",
    "_expand_env",
    "_redact",
]
