"""Nodrix 2.5 canonical backend-neutral System Model."""

from .catalog import DefinitionCatalog
from .compatibility import (
    CompatibilityResult,
    CompatibilityWarning,
    pipeline_manifest_to_system,
    CompatibilityDisposition,
    CompatibilityEntry,
    CompatibilityError,
    CompatibilityReport,
    compatibility_report_from_system,
    restore_pipeline_manifest,
)
from .graph import (
    Connection,
    Graph,
    SystemLink,
    split_local_endpoint,
    split_system_endpoint,
)
from .instances import (
    ApplicationInstance,
    Artifact,
    NodeInstance,
    ResourceInstance,
    Target,
)
from .io import (
    SYSTEM_MODEL_KIND,
    SYSTEM_MODEL_SCHEMA_ID,
    SystemDocumentFormat,
    SystemFormatError,
    SystemLoadResult,
    dump_system,
    dump_system_schema,
    dumps_system,
    load_system,
    load_system_details,
    loads_system,
    system_json_schema,
    system_to_canonical,
)
from .model import SYSTEM_MODEL_API_VERSION, SystemModel
from .planning import (
    SYSTEM_EXECUTION_PLAN_SCHEMA,
    PlannedApplication,
    PlannedArtifact,
    PlannedConnection,
    PlannedGraph,
    PlannedLink,
    PlannedNode,
    PlannedResource,
    PlannedTarget,
    PlanningDiagnostic,
    SystemExecutionPlan,
    SystemPlanningError,
    plan_system,
)
from .validation import (
    SystemDiagnostic,
    SystemValidationError,
    SystemValidationReport,
    validate_system,
)

__all__ = [
    "ApplicationInstance",
    "Artifact",
    "CompatibilityDisposition",
    "CompatibilityEntry",
    "CompatibilityError",
    "CompatibilityReport",
    "compatibility_report_from_system",
    "restore_pipeline_manifest",
    "CompatibilityResult",
    "CompatibilityWarning",
    "Connection",
    "DefinitionCatalog",
    "Graph",
    "NodeInstance",
    "ResourceInstance",
    "SYSTEM_MODEL_KIND",
    "SYSTEM_MODEL_SCHEMA_ID",
    "SystemDocumentFormat",
    "SystemFormatError",
    "SystemLoadResult",
    "dump_system",
    "dump_system_schema",
    "dumps_system",
    "load_system",
    "load_system_details",
    "loads_system",
    "system_json_schema",
    "system_to_canonical",
    "SYSTEM_MODEL_API_VERSION",
    "SystemDiagnostic",
    "SystemLink",
    "SystemModel",
    "SYSTEM_EXECUTION_PLAN_SCHEMA",
    "PlannedApplication",
    "PlannedArtifact",
    "PlannedConnection",
    "PlannedGraph",
    "PlannedLink",
    "PlannedNode",
    "PlannedResource",
    "PlannedTarget",
    "PlanningDiagnostic",
    "SystemExecutionPlan",
    "SystemPlanningError",
    "plan_system",
    "SystemValidationError",
    "SystemValidationReport",
    "Target",
    "pipeline_manifest_to_system",
    "split_local_endpoint",
    "split_system_endpoint",
    "validate_system",
]
